#pragma once
#define EAG_VKEY_A 0
#define EAG_VKEY_B 1
#define EAG_VKEY_C 2
#define EAG_VKEY_D 3
#define EAG_VKEY_E 4
#define EAG_VKEY_F 5
#define EAG_VKEY_G 6
#define EAG_VKEY_H 7
#define EAG_VKEY_I 8
#define EAG_VKEY_J 9
#define EAG_VKEY_K 10
#define EAG_VKEY_L 11
#define EAG_VKEY_M 12
#define EAG_VKEY_N 13
#define EAG_VKEY_O 14
#define EAG_VKEY_P 15
#define EAG_VKEY_Q 16
#define EAG_VKEY_R 17
#define EAG_VKEY_S 18
#define EAG_VKEY_T 19
#define EAG_VKEY_U 20
#define EAG_VKEY_V 21
#define EAG_VKEY_W 22
#define EAG_VKEY_X 23
#define EAG_VKEY_Y 24
#define EAG_VKEY_Z 25
#define EAG_VKEY_0 26
#define EAG_VKEY_1 27
#define EAG_VKEY_2 28
#define EAG_VKEY_3 29
#define EAG_VKEY_4 30
#define EAG_VKEY_5 31
#define EAG_VKEY_6 32
#define EAG_VKEY_7 33
#define EAG_VKEY_8 34
#define EAG_VKEY_9 35
#define EAG_VKEY_LEFT 36
#define EAG_VKEY_UP 37
#define EAG_VKEY_RIGHT 38
#define EAG_VKEY_DOWN 39
#define EAG_VKEY_SHIFT 40
#define EAG_VKEY_CTRL 41
#define EAG_VKEY_ALT 42
#define EAG_VKEY_RETURN 43
#define EAG_VKEY_SPACE 44
#define EAG_VKEY_ESC 45
#define EAG_VKEY_SIZE EAG_VKEY_ESC  // 확인할 전체 키의 갯수